server:
  port: 8080
spring:
  redis:
    lettuce:
      pool:
        max-wait: 60000
        min-idle: 10
        max-idle: 10
        max-active: 16
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/candy?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      connection-timeout: 30000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  executor-type: batch
  configuration:
    auto-mapping-unknown-column-behavior: warning
    map-underscore-to-camel-case: true
    use-actual-param-name: true
debug: true
